# Generated by Django 2.0.13 on 2019-10-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
