# Generated by Django 2.0.13 on 2019-10-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_emailvalid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailValid',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
