# Generated by Django 2.0.13 on 2019-11-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='is_check_article',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='is_check_comment',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
